name: Generate Release Notes
on:
  workflow_call:

jobs:
  get-commits:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: 'main'

    - name: Generate release notes
      uses: vhermawan/generator-release-notes@v1.0.2
      with:
        owner: <your-username>
        token: ${{ github.token }}
        repository: <your-repository-name>
