name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  pull-request:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  generate-release-notes:
    if: contains(github.event.pull_request.labels.*.name, 'release')
    needs: pull-request
    uses: ./.github/workflows/generate-release-note.yml
    secrets: inherit
