name: Publish
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  bump-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: alirezatheh/auto-bump-versions@v1
        with:
          github-token: ${{ secrets.TOKEN }}
          new-version: 0.1.8
          use-bumpver: true
