 name: Build and release
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: maicol07/github-changelog-action@master
        with:
          tag_query: "1.0.0"      
