name: Generate and Commit Changelog

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  generate_changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Bump version
        id: bump_version
        uses: fwilhe2/bump-version@0.1.8
        with:
          component: patch # You can change to major or minor as needed

      - name: Generate Changelog
        id: changelog
        uses: mattiaguida/auto-changelog-action@v2.2.2
        with:
          output: CHANGELOG.md

      - name: Commit and Push Changelog
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "docs: update CHANGELOG.md for version ${{ steps.bump_version.outputs.newVersion }}"
          git push origin HEAD:main

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.bump_version.outputs.newVersion }}
          release_name: ${{ steps.bump_version.outputs.newVersion }}
          body: |
            See the CHANGELOG.md for details on the latest changes.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
